### ISSUE TITLE
what if we just shrimply merged the u22 source with my existing eaglerreborn 1.0 code

### ISSUE THREAD

**Issue by OtterCodes101** [eaglerforge/EaglerForge#1]

**Comment by wxnnvs** [comment]
Smart ass idea

**Comment by STPv22** [comment]
Where did you get the u22 code?

**Comment by OtterCodes101** [comment]
from the eagler discord

**Comment by STPv22** [comment]
Oh

**Comment by evokerking1** [comment]
Sounds awesome.  Would that mean PluginAPI plugins would be compatible w/ eaglerforge?

**Comment by OtterCodes101** [comment]
well duh

**Comment by wxnnvs** [comment]
> well duh

😂

**Comment by STPv22** [comment]
i honestly liked the original design. the eaglerreborn doent look as good.

**Comment by OtterCodes101** [comment]
wtf do you mean "original" design

**Comment by STPv22** [comment]
the one is the screenshot

**Comment by OtterCodes101** [comment]
mine WAS the original as it was developed first

**Comment by STPv22** [comment]
well, I like that better than the one currently.

**Comment by OtterCodes101** [comment]
uhhh radman scrapped that one i think because he couldn't make a scrollbar

**Comment by Legend7832** [comment]
> from the eagler discord

What is the discord link

**Comment by Grant7777** [comment]
[Here you go](https://discord.gg/UhYnFmbAzf)
@Legend7832

**Comment by radmanplays** [comment]
should i close this issue or not?

**Comment by Vexb0t** [comment]
> should i close this issue or not?

this is a historical, cultural issue.

no.

**Comment by OtterCodes101** [comment]
eh lets close it

**Comment by OtterCodes101** [comment]
eaglerforge is basically the successor to eaglerreborn at this point
