### ISSUE TITLE
1.20 Rendering

### ISSUE THREAD

**Issue by Legend7832** [eaglerforge/EaglerForge#11]
### ⠀

Would it be possible to use this mod api to render in 1.20 blocks and items like copper and netherite into 1.8 client?

**Comment by wxnnvs** [comment]
It will i think after some future updates

**Comment by Legend7832** [comment]
i  might make it a suggestion

**Comment by OtterCodes101** [comment]
i think this would be possible via the mcinstance global

**Comment by Legend7832** [comment]
> i think this would be possible via the mcinstance global
I’ll take a look at that

**Comment by Legend7832** [comment]
If someone could create a template with this, I would be grateful because I have no idea where to start

**Comment by PeytonPlayz595** [comment]
It would have to be in a singleplayer world most likely, unless it was a server-side mod too or the server has ViaVersion or sum

**Comment by Legend7832** [comment]
I will be closing this issue. You are welcome to open up another issue on this idea.

**Comment by Legend7832** [comment]
I will be closing this issue. You are welcome to open up another issue on this idea.
