### ISSUE TITLE
add some servers by default like resent

### ISSUE THREAD

**Issue by Atticuss320** [eaglerforge/EaglerForge#13]
### ⠀

(like helltech) lol

**Comment by OtterCodes101** [comment]
boo

**Comment by STPv22** [comment]
do it yourself when you compile the client.

**Comment by STPv22** [comment]
or make a pull request

**Comment by Murturtle** [comment]
down voteeeeee

**Comment by STPv22** [comment]
Then thats A skill issue

**Comment by Legend7832** [comment]
Close the issue, cause this one is an easy fix

**Comment by OtterCodes101** [comment]
> Close the issue, cause this one is an easy fix

based

**Comment by STPv22** [comment]
like honestly they could have done this themselves
