### ISSUE TITLE
Making the new GUI actually work

### ISSUE THREAD

**Issue by leahanderson1** [eaglerforge/EaglerForge#30]
### ⠀

this is a tracker for linking the new GUI to the modloader code

**Comment by ZXMushroom63** [comment]
Made some progress on modloader integration, currently it works by externally hooking into the virtual file system.

**Comment by OtterCodes101** [comment]
oh cool

**Comment by OtterCodes101** [comment]
closed in [33bf7bb](https://github.com/eaglerforge/EaglerForge/commit/33bf7bbfadfdc47e98fd26417d5a038851aee664)
