### ISSUE TITLE
Oversight: NoReflect class “methods” should be an object instead of a list

### ISSUE THREAD

**Issue by OtterCodes101** [eaglerforge/EaglerForge#32]
### Discussed in https://github.com/orgs/eaglerforge/discussions/31

<div type='discussions-op-text'>

<sup>Originally posted by **lax1dude** June 11, 2024</sup>
Hi guys I have one more suggestion to try and make what you’re trying to do here work a bit better.

This discrepancy might seem insignificant on its own but if you look at the “tracers.js” example mod, the current recommended way to use NoReflect is to define helper functions like `mathHelperFunction(name, args)` to use for calling the exported NoReflect functions, which are implemented in a way that iterates over the ENTIRE list of exported functions in the NoReflect class each time to find it first in order to call it.

```
function mathHelperFunction(name, args) {
    return classes.MathHelper.methods.filter((method) => {
        return method.methodName === name
    })[0].exec(args);
}
```

This is the worst possible way it could’ve been implemented for performance, the browser isn’t smart enough to see what you’re trying to do here and optimize it, it will iterate over every element in the list and attempt to compare the name of every function regardless if the function you’re searching for is the first or very last on the list before returning and actually calling it. This process is then repeated every time the function needs to be called again.

You need to change it so “methods” is an object (`{}`) instead of a list (`[]`) and indexes all the methods into it by method name. That way when you go to call a method by name, you can just do `methods.methodNameHere.exec(args)` and the underlying JavaScript engine will automatically compute a hashtable of all the names of the functions in the NoReflect class to be able search it for the right functions orders of magnitude faster than the current implementation can. This also completely eliminates the need for the helper functions in the “tracers.js” making it easier to work with.

I hope you understand my concerns, you’d have to break compatibility with existing mods in order to fix this so I thought it’s better to point it out sooner than later.</div>

**Comment by ZXMushroom63** [comment]
Not oversight, see _https://github.com/eaglerforge/EaglerForge/discussions/31#discussioncomment-9748270_
