### ISSUE TITLE
Build_init not working but client compiling fine

### ISSUE THREAD

**Issue by STPv22** [eaglerforge/EaglerForge#43]
### by requesting a bug you must check these boxes

- [X] I have explained about the bug(s)
- [X] I have left attachments or code lines
- [X] I know that I won't waste your time
- [X] I just checked all of these boxes without reading the labels

### about the bug

build_init task fails to run with java 17 installed on winows 11. CompileLatestClient runs successfully, as does actual MCP.

- [X] I Just checked all of the boxes without reading the labels

### Screenshots

![image](https://github.com/user-attachments/assets/c7b73061-000b-42b7-98e8-4fcb3235c53f)

**Comment by STPv22** [comment]
I haven't tried actual eagler

**Comment by OtterCodes101** [comment]
![image](https://github.com/user-attachments/assets/eabb2c28-bf70-4287-8450-03506d56a5b2)
guh

**Comment by Project516** [comment]
Oh u may of put in the wrong json file

**Comment by Project516** [comment]
It is the 1.8json not 1.8.8

**Comment by Project516** [comment]
U also need fmpeg on path I think

**Comment by STPv22** [comment]
no I just need the Exe file

**Comment by STPv22** [comment]
> It is the 1.8json not 1.8.8

oh ok where?

**Comment by STPv22** [comment]
> ![image](https://private-user-images.githubusercontent.com/144633084/357891707-eabb2c28-bf70-4287-8450-03506d56a5b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NTYyNzEsIm5iZiI6MTcyMzY1NTk3MSwicGF0aCI6Ii8xNDQ2MzMwODQvMzU3ODkxNzA3LWVhYmIyYzI4LWJmNzAtNDI4Ny04NDUwLTAzNTA2ZDU2YTViMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxNzE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzY1MWVmOWU1Y2UzMmI0MThjMWI1OTI4ODNhYzkzOGIyZmI2ZjAxNmFjYzNlMmFmMjZkMWY4ZWQxYzYyZTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yp-mUGS-tcU_WkobuMtBg1jgwKbKiEqhE1HprteGn-s) guh

im joking

**Comment by Project516** [comment]
> > It is the 1.8json not 1.8.8
> 
> oh ok where?

Right here https://www.minecraft.net/en-us/store/minecraft-java-bedrock-edition-pc

**Comment by STPv22** [comment]
You mean 1.8 java version?

**Comment by STPv22** [comment]
Ok. But there was one already on the folder

**Comment by STPv22** [comment]
ok, retrying...

**Comment by STPv22** [comment]
yup, that was it, thx

**Comment by STPv22** [comment]
the workspace wont compile now cause it can't find teavm

**Comment by STPv22** [comment]
I just dragged the src file into the normal workspace and it worked. worry for the notification.
