### ISSUE TITLE
Can i put this on my website?  It is https://github.com/evokerking1/eaglerforge 

### ISSUE THREAD

**Issue by evokerking1** [eaglerforge/EaglerForge#5]
### ⠀

I have not modified it any way so it as original as possible

**Comment by radmanplays** [comment]
ofc you can. just download the "web.zip" file from [this link](https://github.com/eaglerforge/EaglerForge-builds/releases/tag/release) and upload the contents of it to github

**Comment by evokerking1** [comment]
> ofc you can. just download the "web.zip" file from [this link](https://github.com/eaglerforge/EaglerForge-builds/releases/tag/release) and upload the contents of it to github

Thanks I was just gonna make it more accessible

**Comment by evokerking1** [comment]
> ofc you can. just download the "web.zip" file from [this link](https://github.com/eaglerforge/EaglerForge-builds/releases/tag/release) and upload the contents of it to github

Can you add my website version to the README as a demo version?
