### ISSUE TITLE
game crashes whenever i try to load a new mod

### ISSUE THREAD

**Issue by STPv22** [eaglerforge/EaglerForge#7]
### by requesting a bug you must check these boxes

- [X] I have explained about the bug(s)
- [X] I have left attachments or code lines
- [X] I know that I won't waste your time
- [ ] I just checked all of these boxes without reading the labels

### about the bug

The mods save, but then fail to load when i reload the page.

error message:
Game Crashed! I have fallen and I can't get up!

Native Browser Exception
----------------------------------
  Line: data:text/javascript,var%20isToggled%20%3D%20false%3B%20%2F%2Fstores%20whether%20the%20plugin%20is%20on%20or%20off%0Avar%20oldBrightness%20%3D%20PluginAPI.blocks.air.lightValue%20%2F%2Fstores%20the%20original%20lightvalue%0A%0A%0Awindow.addEventListener(%22keydown%22%2C%20(event)%20%3D%3E%20%7B%0A%20%20%20%20if%20(event.key.toLowerCase()%20%3D%3D%3D%20%22f%22)%20%7B%0A%20%20%20%20%20%20%20%20isToggled%20%3D%20!isToggled%3B%0A%20%20%20%20%20%20%20%20if%20(isToggled)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20PluginAPI.blocks.air.lightValue%20%3D%2010%3B%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20PluginAPI.blocks.air.lightValue%20%3D%20oldBrightness%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20PluginAPI.blocks.reload()%3B%0A%20%20%20%20%20%20%20%20PluginAPI.displayToChat(%7Bmsg%3A%20%22Fullbright%20toggled%20%22%20%2B%20isToggled%7D)%0A%20%20%20%20%7D%0A%7D)%3B:2:21
  Type: ReferenceError
  Desc: PluginAPI is not defined
----------------------------------

ReferenceError: PluginAPI is not defined
    at data:text/javascript,var%20isToggled%20%3D%20false%3B%20%2F%2Fstores%20whether%20the%20plugin%20is%20on%20or%20off%0Avar%20oldBrightness%20%3D%20PluginAPI.blocks.air.lightValue%20%2F%2Fstores%20the%20original%20lightvalue%0A%0A%0Awindow.addEventListener(%22keydown%22%2C%20(event)%20%3D%3E%20%7B%0A%20%20%20%20if%20(event.key.toLowerCase()%20%3D%3D%3D%20%22f%22)%20%7B%0A%20%20%20%20%20%20%20%20isToggled%20%3D%20!isToggled%3B%0A%20%20%20%20%20%20%20%20if%20(isToggled)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20PluginAPI.blocks.air.lightValue%20%3D%2010%3B%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20PluginAPI.blocks.air.lightValue%20%3D%20oldBrightness%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20PluginAPI.blocks.reload()%3B%0A%20%20%20%20%20%20%20%20PluginAPI.displayToChat(%7Bmsg%3A%20%22Fullbright%20toggled%20%22%20%2B%20isToggled%7D)%0A%20%20%20%20%7D%0A%7D)%3B:2:21

eaglercraft.version = "v1"
eaglercraft.minecraft = "1.8.8"
eaglercraft.brand = "radmanplays"
eaglercraft.username = "DANGERalt"

webgl.version = WebGL 2.0 (OpenGL ES 3.0 Chromium)
webgl.renderer = ANGLE (Intel, Mesa Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)
webgl.vendor = Google Inc. (Intel)

webgl.ext.HDR16f = true
webgl.ext.HDR32f = true

window.eaglercraftXOpts = {"container":"game_frame","relays":[{"addr":"wss://relay.deev.is/","primary":false,"comment":"lax1dude relay #1"},{"addr":"wss://relay.lax1dude.net/","primary":true,"comment":"lax1dude relay #2"},{"addr":"wss://relay.shhnowisnottheti.me/","primary":false,"comment":"ayunami relay #1"}],"assetsURI":"data:application/octet-stream;base64,RUFHUEtHJCQGdmVyMi4wCmFzc2V0cy5lcGsAUgoKICMgIEVhZ2xlciBFUEsgdjIuMCAoYykgMjAyNCBsYXgxZHVkZQo ... ","worldsDB":"worlds"}

currentTime = Mon, 19 Feb 2024 16:54:24 +0000

window.navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
window.navigator.vendor = Google Inc.
window.navigator.language = en-US
window.navigator.hardwareConcurrency = 2
window.navigator.deviceMemory = 4
window.navigator.platform = Linux x86_64
window.navigator.product = Gecko

rootElement.clientWidth = 1300
rootElement.clientHeight = 731
window.innerWidth = 1300
window.innerHeight = 731
window.outerWidth = 1300
window.outerHeight = 730
window.devicePixelRatio = 1.0507692098617554
window.screen.availWidth = 1300
window.screen.availHeight = 730
window.screen.colorDepth = 24
window.screen.pixelDepth = 24

window.currentContext = undefined

window.location.href = file:///home/chronos/u-e3e893b1177613152a88fea57625b1cc8cf7f361/MyFiles/Downloads/Egg%20u19%20source/MACOS_X/EaglerForge_v1_1.8_Offline_en_US.html

**Comment by OtterCodes101** [comment]
shrimply add a new mod with
```js
PluginAPI = ModAPI;
```
inside

**Comment by STPv22** [comment]
ok.

**Comment by STPv22** [comment]
is the ModAPI any different from the pluginAPI?

**Comment by STPv22** [comment]
shiiii.... now the game crashes whenever i open the game... this time its v1.1

**Comment by STPv22** [comment]
add a "load without mods" plz

**Comment by STPv22** [comment]
tried that, didn't work.

**Comment by wxnnvs** [comment]
@STPv22 
either modify the mods with `var PluginAPI = ModAPI` or rewrite all instances of `PluginAPI` to `ModAPI`
